### ISSUE TITLE
Focus.focus shows a "paste" menu

### ISSUE THREAD

**Issue by zmandel** [46cl/cordova-android-focus-plugin#1]
Thanks for this plugin. on android 4.4 it does set the focus and displays the keyboard, but it also shows a little "Paste" menu item on the focused element. My element is type number.

**Comment by jvelo** [comment]
Hi, thanks for reporting this ; could you provide a screenshot ? (I've never seen this behavior). Also, what device was used ?

**Comment by zmandel** [comment]
on samsung s5. Does not always happen. Seems like sometimes it thinks its a
long click. I dont have the phone available today but will post a
screenshot later. It shows a menu with a single item "paste".

**Comment by zmandel** [comment]
In your java code i see maybe if you saved the millis value in a variable
it will guarantee the same value on the down and up click

Zig Mandel

**Comment by zmandel** [comment]
Ive tried what I suggested above but doesnt fix it.
whenever the keyboard takes a little longer to display, the "paste" menu appears.

**Comment by zmandel** [comment]
So, my suggested fix does work. I will send a pull request

**Comment by jvelo** [comment]
Merged, thanks!
