### ISSUE TITLE
when webview is scrolled, click goes to wrong place

### ISSUE THREAD

**Issue by zmandel** [46cl/cordova-android-focus-plugin#4]
Repro: vertically scroll the webview. Issue the plugin focus.
result: click will go above the area is supposed to click.

Expected: to consider possible x and y scroll

**Comment by zmandel** [comment]
I will give a shot at fixing this one too. That other fix i pushed was my first java code ever :)

**Comment by jvelo** [comment]
I guess the proper way to fix this is to account for scroll position in the JS part, before sending the coordinates to the Java plugin

**Comment by zmandel** [comment]
yes, its here https://github.com/46cl/cordova-android-focus-plugin/pull/5
