### ISSUE TITLE
on android 4.0 no click is sent

### ISSUE THREAD

**Issue by zmandel** [46cl/cordova-android-focus-plugin#6]
I have tried on the android emulator 4.0 (api level 14), and it does not appear to send the click. element does not gain focus and keyboard doesnt pop.
It does work on 4.4.2.

I have tried to debug by making a minimal sample and even then it does not click the element.
Any ideas what could be going on?

**Comment by zmandel** [comment]
ive shown that the javascript does calculate a reasonable rect and it calls exec, but I dont know how to debug it furhter. From the documentation, it seems that the java code should work on 4.0 but it isnt.
I doubt its an emulator issue as it does work in 4.4 in emulator,

**Comment by zmandel** [comment]
alright, I found the problem and will send you soon a pull request as soon as I get some sleep.

**Comment by jvelo** [comment]
Merged, thanks

**Comment by zmandel** [comment]
thanks and sorry for the jquery dependency, looks great now.
