### ISSUE TITLE
build failed with android cordova 4.0.0

### ISSUE THREAD

**Issue by puntsok** [46cl/cordova-android-focus-plugin#9]
I am having trouble compiling with the latest version of cordova android:

``` shell
Installed platforms: android 4.0.0
```

Most likely the problem is how the `CordovaWebView` no longer extends its parent in the same way as it did before.  Several other plugins are also dealing with the same issue (e.g. com.telerik.plugins.nativepagetransitions, de.appplant.cordova.plugin.local-notification). Here is the error section of output log upon `cordova build android`: 

``` shell
:compileArmv7DebugJava
/Users/cewalker/Sites/hello/platforms/android/src/fr/_46cl/focus/Focus.java:55: error: cannot find symbol
                webView.dispatchTouchEvent(MotionEvent.obtain(uMillis, uMillis, MotionEvent.ACTION_DOWN, centerLeft, centerTop, 0));
                       ^
  symbol:   method dispatchTouchEvent(MotionEvent)
  location: variable webView of type CordovaWebView
/Users/cewalker/Sites/hello/platforms/android/src/fr/_46cl/focus/Focus.java:56: error: cannot find symbol
                webView.dispatchTouchEvent(MotionEvent.obtain(uMillis, uMillis, MotionEvent.ACTION_UP, centerLeft, centerTop, 0));
                       ^
  symbol:   method dispatchTouchEvent(MotionEvent)
  location: variable webView of type CordovaWebView
2 errors
:compileArmv7DebugJava FAILED
```

Wish I could contribute a fix, but I'm not familiar enough with the android platform.  Is there a quick fix for this?

Cheers!

**Comment by jvelo** [comment]
Hi,

Thanks for the report. I've checked the updated CordovaWebView interface, and it seems now you need to call its getView() method to access the actual view : https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebView.java#L40
I'll try to fix this rapidly.

Jerome

**Comment by ghost** [comment]
Hello,

I am having the same issue using Cordova 5.1.1. Is this easily fixable?

**Comment by jvelo** [comment]
Hi, I've merged the pending PR, should be OK now. Thanks @puntsok.
